### ISSUE TITLE
Installation error in Building database schema

### ISSUE THREAD

**Issue by abstractk** [silverstripe/recipe-core#32] opened 2018-10-30 11:53 UTC
Using recipe-code version 4.2.1. After all dependencies are installed and after filling in the details in install.php page, I'm getting this error

```
I am now running through the installation steps (this should take about 30 seconds)

If you receive a fatal error, refresh this page to continue the installation

Setting up public/index.php
Setting up app/_config.php
Setting up app/_config/theme.yml
Setting up .env
Setting up /var/www/app/app/src/RootURLController.php
Building database schema...
ERROR [Emergency]: Uncaught Error: Class 'SilverStripe\Versioned\Versioned' not found IN POST /install.php Line 112 in /var/www/app/vendor/silverstripe/assets/src/Shortcodes/FileLinkTracking.php Source ====== 103: $this->owner->extend('augmentSyncLinkTracking'); 104: } 105: 106: /** 107: * Find HTMLText fields on {@link owner} to scrape for links that need tracking 108: */ 109: public function augmentSyncLinkTracking() 110: { 111: // If owner is versioned, skip tracking on live * 112: if (Versioned::get_stage() == Versioned::LIVE && $this->owner->hasExtension(Versioned::class)) { 113: return; 114: } 115: 116: // Build a list of HTMLText fields, merging all linked pages together. 117: $allFields = DataObject::getSchema()->fieldSpecs($this->owner); 118: $linkedPages = []; Trace ===== SilverStripe\Assets\Shortcodes\FileLinkTracking->augmentSyncLinkTracking(, , , , , , ) Extensible.php:464 SilverStripe\View\ViewableData->extend(augmentSyncLinkTracking) FileLinkTracking.php:103 SilverStripe\Assets\Shortcodes\FileLinkTracking->syncLinkTracking() call_user_func_array(Array, Array) Extensible.php:143 SilverStripe\View\ViewableData->SilverStripe\Core\{closure}(SilverStripe\Security\Group, Array) CustomMethods.php:61 SilverStripe\View\ViewableData->__call(syncLinkTracking, Array) FileLinkTracking.php:92 SilverStripe\Assets\Shortcodes\FileLinkTracking->onBeforeWrite(, , , , , , ) Extensible.php:464 SilverStripe\View\ViewableData->extend(onBeforeWrite, ) DataObject.php:1188 SilverStripe\ORM\DataObject->onBeforeWrite() Group.php:513 SilverStripe\Security\Group->onBeforeWrite() DataObject.php:1334 SilverStripe\ORM\DataObject->preWrite() DataObject.php:1495 SilverStripe\ORM\DataObject->write() Group.php:661 SilverStripe\Security\Group->requireDefaultRecords() DatabaseAdmin.php:386 SilverStripe\ORM\DatabaseAdmin->doBuild(1) Installer.php:175 SilverStripe\Dev\Install\Installer->SilverStripe\Dev\Install\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) HTTPApplication.php:66 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:67 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, 1) Installer.php:202 SilverStripe\Dev\Install\Installer->install(Array) install5.php:130 include(/var/www/app/vendor/silverstripe/framework/src/Dev/Install/install5.php) install.php:25 include(/var/www/app/vendor/silverstripe/framework/src/Dev/Install/install.php) install.php:15
```

**Comment by robbieaverill** [comment] 2018-10-30 16:12
Duplicate of #31

**Closed by robbieaverill** 2018-10-30 16:12 UTC
